---
collections:
  - name: infra.leapp
  - name: ansible.posix
    version: ">=1.5.1"
  - name: community.general
    version: ">=6.6.0"
  - name: fedora.linux_system_roles # or redhat.rhel_system_roles see upgrade readme for more details
    version: ">=1.21.0"
