---
- name: Analysis
  hosts: rhel6 
  strategy: free
  gather_facts: true
  become: true
  force_handlers: true

  tasks:
    - name: Generate preupgrade analysis report
      ansible.builtin.import_role:
        name: infra.leapp.analysis
