---
- name: Upgrade
  hosts: rhel6 
  strategy: free
  become: true
  force_handlers: true
  vars:
    rhel_7_network_install_repo_url: http://rhel8-sat01.kenlab.local/pub/RHEL7.9/
      
  tasks:
    - name: Perform OS upgrade
      ansible.builtin.import_role:
        name: infra.leapp.upgrade
